### PR TITLE
Update DOI resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
See diff & https://www.doi.org/doi_handbook/3_Resolution.html#3.8 ;-)

### CODE REVIEW

**Comment by jeremyf** [comment]
@katrinleinweber Sorry about the late follow-up. I am not seeing whether or not you have a signed and submitted CLA. Please see https://wiki.lyrasis.org/display/samvera/Samvera+Community+Intellectual+Property+Licensing+and+Ownership

**Comment by katrinleinweber** [comment]
That process seems longer than the URL (not code) update I'm suggesting. There's certainly nothing I'd consider IP in this PR.

**Comment by jeremyf** [comment]
While the process may be more involved, that is the requirements for merging any code changes.

**Review by jeremyf — CHANGES_REQUESTED** [review]
Before we can merge, we'll need a CLA.

**Comment by katrinleinweber** [comment]
I'll not jump through such hoops. Maybe you could switch to @clabot?

**Pull request closed without merging**
